# Generated by Django 4.0.6 on 2023-01-16 14:25

import ckeditor.fields
import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', ckeditor.fields.RichTextField()),
            ],
        ),
        migrations.CreateModel(
            name='CostsMembers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cost Member',
                'verbose_name_plural': 'Costs Member',
            },
        ),
        migrations.CreateModel(
            name='MemberPeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField()),
                ('date_finished', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_activate', models.DateField(default=datetime.date.today, verbose_name='Date activate')),
                ('payment_cost', models.CharField(default='', max_length=50, verbose_name='payment type')),
                ('amount', models.IntegerField(default=0, verbose_name='Amount')),
                ('payment_method', models.CharField(default='', max_length=50, verbose_name='Payment method')),
                ('payment_comment', models.CharField(blank=True, default='', max_length=210, verbose_name='')),
                ('is_member', models.BooleanField(default=False)),
                ('date_period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.memberperiod', verbose_name='Period')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Member')),
            ],
        ),
    ]
