# Generated by Django 4.0.6 on 2023-01-16 14:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0002_typemember'),
    ]

    operations = [
        migrations.AlterField(
            model_name='costsmembers',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='member.typemember', verbose_name='Type'),
        ),
    ]
