# Generated by Django 4.0.6 on 2023-04-10 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0004_member_type_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='payment_cost',
            field=models.CharField(default='', max_length=50, verbose_name='payment cost'),
        ),
        migrations.AlterField(
            model_name='member',
            name='type_member',
            field=models.CharField(max_length=50, verbose_name='Member type'),
        ),
    ]
