# Generated by Django 4.0.6 on 2023-01-11 17:13

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=50, verbose_name='')),
                ('price', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Cost',
                'verbose_name_plural': 'Costs',
            },
        ),
        migrations.CreateModel(
            name='DaysTournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='')),
                ('time_start', models.TimeField(blank=True, null=True)),
                ('time_finished', models.TimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Day Event',
                'verbose_name_plural': 'Days Event',
            },
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Level',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Tournament')),
                ('place', models.CharField(default='', max_length=80)),
                ('condition', models.BooleanField(default=False)),
                ('public', models.BooleanField(default=False)),
                ('members', models.BooleanField(default=False)),
                ('details', ckeditor.fields.RichTextField(default='')),
                ('day', models.ManyToManyField(to='tournament.daystournament')),
                ('division', models.ManyToManyField(to='tournament.division')),
                ('level', models.ManyToManyField(blank=True, to='tournament.level')),
                ('payment', models.ManyToManyField(to='tournament.payment')),
                ('payment_cost', models.ManyToManyField(blank=True, to='tournament.costs')),
                ('type', models.ManyToManyField(to='tournament.type')),
            ],
            options={
                'verbose_name': 'Event',
                'verbose_name_plural': 'Events',
            },
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_comment', models.CharField(blank=True, default='', max_length=80, verbose_name='')),
                ('partner', models.CharField(blank=True, max_length=50, null=True)),
                ('conflicts', models.TextField(blank=True, max_length=100, null=True)),
                ('parent', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('parent_relation', models.CharField(blank=True, choices=[('1', 'Mather'), ('2', 'Father'), ('3', 'Other')], max_length=50, null=True, verbose_name='')),
                ('email_parent', models.EmailField(blank=True, max_length=254, null=True, verbose_name='')),
                ('phone_parent', models.CharField(blank=True, max_length=50, null=True, verbose_name='')),
                ('condition', models.BooleanField(default=False)),
                ('day_time', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.daystournament', verbose_name='Select Day Time')),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.division', verbose_name='Select Division')),
                ('level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.level', verbose_name='Select Level')),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.payment', verbose_name='Select Payment')),
                ('payment_cost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.costs', verbose_name="Select Cost you'll pay")),
            ],
        ),
    ]
