# Generated by Django 4.0.6 on 2023-01-13 16:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tournament', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='daystournament',
            options={'verbose_name': 'Event Date', 'verbose_name_plural': 'Event Dates'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'verbose_name': 'Payment Method', 'verbose_name_plural': 'Payment Methods'},
        ),
        migrations.AlterField(
            model_name='costs',
            name='category',
            field=models.CharField(max_length=50, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.payment', verbose_name='Select Payment method'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Participan'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='tournament',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.tournament', verbose_name='Event'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Event'),
        ),
    ]
