# Generated by Django 4.0.6 on 2023-02-24 19:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['date'], 'verbose_name': 'Event', 'verbose_name_plural': 'Events'},
        ),
        migrations.AddField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name=''),
        ),
    ]
