# Generated by Django 4.0.6 on 2023-03-14 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_tournament_options_tournament_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Start'),
        ),
    ]
