# Generated by Django 4.0.6 on 2023-01-16 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_alter_daystournament_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='day_time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tournament.daystournament', verbose_name='Date time'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='division',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.division', verbose_name='Division'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='email_parent',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Parent email'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.level', verbose_name='Level'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='parent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='parent_relation',
            field=models.CharField(blank=True, choices=[('1', 'Mather'), ('2', 'Father'), ('3', 'Other')], max_length=50, null=True, verbose_name='Parent relation'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.payment', verbose_name='Payment method'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_comment',
            field=models.CharField(blank=True, max_length=80, verbose_name='Payment comment'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='payment_cost',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tournament.costs', verbose_name='Payment cost'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='phone_parent',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Parent phone'),
        ),
    ]
