# Generated by Django 4.0.6 on 2023-03-14 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_alter_tournament_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='list_public',
            field=models.BooleanField(default=False, verbose_name='Public List'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='condition',
            field=models.BooleanField(default=False, verbose_name='Visible'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='members',
            field=models.BooleanField(default=False, verbose_name='for Members'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='public',
            field=models.BooleanField(default=False, verbose_name='for Public'),
        ),
    ]
