# Generated by Django 4.0.6 on 2023-01-11 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='Day')),
                ('persons', models.IntegerField(verbose_name='Persons')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Activity',
                'verbose_name_plural': 'Activities',
            },
        ),
        migrations.CreateModel(
            name='ActivityName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='OtherEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('other_event', models.CharField(max_length=50, verbose_name='')),
            ],
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, verbose_name='emali:')),
                ('phone', models.CharField(max_length=40)),
                ('activities', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.activities', verbose_name='Your chosen activity')),
            ],
        ),
        migrations.CreateModel(
            name='ActivityTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.TimeField(verbose_name='')),
                ('time_finish', models.TimeField(verbose_name='')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.activityname', verbose_name='')),
            ],
        ),
        migrations.AddField(
            model_name='activities',
            name='activity_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.activitytime', verbose_name='Time'),
        ),
        migrations.AddField(
            model_name='activities',
            name='other_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='general.otherevent', verbose_name='Event'),
        ),
    ]
