# Generated by Django 4.0.6 on 2023-04-10 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_newsletter_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newsletter',
            name='body',
            field=models.TextField(blank=True, null=True),
        ),
    ]
