# Generated by Django 4.0.6 on 2023-04-12 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_newsletter_body'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Newsletter',
        ),
    ]
